#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
AW="Award Winning Books- Book Covers"
BK="Book Covers"
NW="Newly Released Books Covers"
NU="with new updates/ABC Books /NEW UPDATE _  NEW BOOK COVER"
DEST="site/src/assets/covers"
mkdir -p "$DEST" "site/src/assets/photos" "site/public/images"

# From "Award Winning Books- Book Covers" (16)
cp "$AW/A Whale in Prison (3).png"                          "$DEST/a-whale-in-prison.png"
cp "$AW/BAREFOOT BULAYAN (COVER).jpg"                       "$DEST/barefoot-bulayan.jpg"
cp "$AW/BULUL (COVER).jpg"                                  "$DEST/bulul.jpg"
cp "$AW/DEAREST PAPA (COVER).jpg"                           "$DEST/dearest-papa.jpg"
cp "$AW/DIOLA - HEROINE IF PHILIPPINE EAGLE (COVER).jpg"    "$DEST/diola-heroine-of-philippine-eagles.jpg"
cp "$AW/I LOVE TNALAK (COVER).jpg"                          "$DEST/i-love-tnalak.jpg"
cp "$AW/MALONG THE MAGIC CLOTH (COVER).jpg"                 "$DEST/malong-the-magic-cloth.jpg"
cp "$AW/PENCIL WHO WOULD NOT WRITE (COVER).jpg"             "$DEST/the-pencil-who-would-not-write.jpg"
cp "$AW/Si Kamatis Inis (1).png"                            "$DEST/si-kamatis-inis.png"
cp "$AW/The Brave Little Stump (1).png"                     "$DEST/the-brave-little-stump.png"
cp "$AW/THE CRYING TREES (COVER).jpg"                       "$DEST/the-crying-trees.jpg"
cp "$AW/THE LITTLE SEED (COVER).jpg"                        "$DEST/the-little-seed.jpg"
cp "$AW/THE OPPOSITE JARS (COVER).jpg"                      "$DEST/the-opposite-jars.jpg"
cp "$AW/THE SMELLY FRUIT (COVER).jpg"                       "$DEST/the-smelly-fruit.jpg"
cp "$AW/WAR MAKES ME SAD (COVER).jpg"                       "$DEST/war-makes-me-sad.jpg"
cp "$AW/WHY IS A PIG_S NOSE FLAT (COVER).jpg"               "$DEST/why-is-a-pigs-nose-flat.jpg"

# From "Book Covers" (34)
cp "$BK/A BASKET IN WAR (COVER).jpg"                        "$DEST/a-basket-in-war.jpg"
cp "$BK/A great miracle.png"                                "$DEST/a-great-miracle.png"
cp "$BK/Ako ay Pilipino.jpg"                                "$DEST/ako-ay-pilipino.jpg"
cp "$BK/Bakit ang Manok ay Walang Ngipin.jpeg"              "$DEST/bakit-walang-ngipin-ang-mga-manok.jpeg"
cp "$BK/BAKIT MALINIS ANG NGIPIN NG BUWAYA (1).png"         "$DEST/bakit-malinis-ang-ngipin-ng-buwaya.png"
cp "$BK/Cindys 365.png"                                     "$DEST/cindys-365-bags-and-more.png"
cp "$BK/Crossing the Red Sea.png"                           "$DEST/crossing-the-red-sea.png"
cp "$BK/Daniel in  the Lion_s Den.png"                      "$DEST/daniel-in-the-lions-den.png"
cp "$BK/Dessert Town is melting.jpg"                        "$DEST/dessert-town-is-melting.jpg"
cp "$BK/Don_t Take My Colors Away.jpg"                      "$DEST/dont-take-my-colors-away.jpg"
cp "$BK/EL AND EY (COVER).jpg"                              "$DEST/el-and-ey.jpg"
cp "$BK/Fluffy_s Misadventure Week It_s All Gone.jpeg"      "$DEST/fluffys-misadventure-week.jpeg"
cp "$BK/FLYING TRASH (COVER).jpg"                           "$DEST/flying-trash.jpg"
cp "$BK/Grandma_s Baked Goodies.jpeg"                       "$DEST/grandmas-baked-goodies.jpeg"
cp "$BK/HOME IS WHERE THE HEART LIVES (COVER).jpg"          "$DEST/home-is-where-the-heart-lives.jpg"
cp "$BK/Jesus Feeds 5000 People.png"                        "$DEST/jesus-feeds-5000-people.png"
cp "$BK/Jesus Heals The Blind (1).png"                      "$DEST/jesus-heals-the-blind.png"
cp "$BK/Jesus Walks on Water (1).png"                       "$DEST/jesus-walks-on-water.png"
cp "$BK/kingdom.png"                                        "$DEST/the-kingdom-with-no-stories.png"
cp "$BK/May Aswang sa School.jpg"                           "$DEST/may-aswang-sa-iskul.jpg"
cp "$BK/MEANINGFUL VALUES FOR GOD_S CHILDREN (COVER).jpg"   "$DEST/meaningful-values-for-gods-children.jpg"
cp "$BK/Mom_s Best Pladough_Dinasaurs_300dpi.png"           "$DEST/moms-best-playdough-dinosaurs.png"
cp "$BK/Mom_s Best Playdough Activities-Philippine National Symbols.png" "$DEST/moms-best-playdough-philippine-national-symbols.png"
cp "$BK/MOM_S BEST PLAYDOUGH BREAD & PASTRIES (COVER).jpg"  "$DEST/moms-best-playdough-bread-pastries.jpg"
cp "$BK/Mom_s Best Playdough Community Helpers.jpg"         "$DEST/moms-best-playdough-community-helpers.jpg"
cp "$BK/MOM_S BEST PLAYDOUGH FARM ANIMALS (COVER).jpg"      "$DEST/moms-best-playdough-farm-animals.jpg"
cp "$BK/MOM_S BEST PLAYDOUGH WILD ANIMALS (COVER).jpg"      "$DEST/moms-best-playdough-wild-animals.jpg"
cp "$BK/MY MUSLIM FRIEND (COVER OLD).jpg"                   "$DEST/my-muslim-friend.jpg"
cp "$BK/My Pink Spot.jpg"                                   "$DEST/my-pink-spot.jpg"
cp "$BK/THE HAIRY FRUIT (COVER).jpg"                        "$DEST/the-hairy-fruit.jpg"
cp "$BK/Tuna Festival.jpeg"                                 "$DEST/tuna-festival.jpeg"
cp "$BK/Two Hats, One Heart_300dpi.png"                     "$DEST/two-hats-one-heart.png"
cp "$BK/Where Shall We Build Our Nest (1).png"              "$DEST/where-shall-we-build-our-nest.png"

# From "Newly Released Books Covers" (12)
cp "$NW/A Crumpled Piece of Paper.png"                      "$DEST/a-crumpled-piece-of-paper.png"
cp "$NW/BALLOONS FLY ANIMALS CRY.jpg"                       "$DEST/balloons-fly-animals-cry.jpg"
cp "$NW/BE YOURSELF, BE BRAVE.jpg"                          "$DEST/be-yourself-be-brave.jpg"
cp "$NW/DON_T TOUCH THE STARFISH (1).jpg"                   "$DEST/dont-touch-the-starfish.jpg"
cp "$NW/Learning About The Philippines Counting Book.jpeg"  "$DEST/learning-about-the-philippines-counting-book.jpeg"
cp "$NW/MGA KILALANG YAMAN NG PILIPINAS.jpg"                "$DEST/mga-kilalang-yaman-ng-pilipinas.jpg"
cp "$NW/MOTHER TURTLE_S NEST.jpg"                           "$DEST/mother-turtles-nest.jpg"
cp "$NW/My Father, The Honest Mayor (3).png"                "$DEST/my-father-the-honest-mayor.png"
cp "$NW/PURPLE HANDS LOVING HANDS.jpg"                      "$DEST/purple-hands-loving-hands.jpg"
cp "$NW/Si Karla feeling Prinsesa (4).png"                  "$DEST/si-karla-feeling-prinsesa.png"
cp "$NW/The Flood Took Lyka Away.jpg"                       "$DEST/the-flood-took-lyka-away.jpg"
cp "$NW/THE LOG OF HOPE.jpg"                                "$DEST/the-log-of-hope.jpg"

# From the "with new updates" delivery, Aug 2026 (4). The three Facebook-export
# filenames were identified by opening each image; the fourth finally supplies
# the cover that Jesus Raises Lazarus From The Dead had been missing.
cp "$NU/768442062_1603869451310761_4521152239130920427_n.jpg" "$DEST/a-mothers-love-in-every-hop.jpg"
cp "$NU/767755473_2079541216020900_4691013290563637310_n.jpg" "$DEST/amihans-colorful-coconut-leaf-slippers.jpg"
cp "$NU/767996163_1582376426727271_5058527348781586774_n.jpg" "$DEST/memories-of-agila.jpg"
cp "$NU/Jesus Raises Lazarus from the Dead.png"                "$DEST/jesus-raises-lazarus-from-the-dead.png"

# Author photos
cp "$AW/Mary Ann Ordinario/Ms Mary Ann.png"                 "site/src/assets/photos/mary-ann-portrait.png"
cp "$AW/Mary Ann Ordinario/m.png"                           "site/src/assets/photos/mary-ann-nbdb.png"
cp "$AW/Mary Ann Ordinario/Ms Mary Ann.png"                 "site/public/images/mary-ann-portrait.png"

echo "Copied $(ls "$DEST" | wc -l | tr -d ' ') covers"
